version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: superland_db
    restart: always
    environment:
      POSTGRES_DB: superland_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: superland_backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/superland_db?schema=public
      JWT_SECRET: sua_chave_secreta_muito_segura_aqui
      PORT: 4000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: superland_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://backend:4000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
